PREFIX DS1211: <http://logd.tw.rpi.edu/source/data-gov/dataset/1211/vocab/raw/>

SELECT ?state (COUNT(?carf_accredit) as ?max_positive_accreditation)
WHERE {

GRAPH <http://logd.tw.rpi.edu/source/data-gov/dataset/1211/version/1st-anniversary>  {	
				?s2 DS1211:carf_accreditation ?carf_accredit.
				?s2 DS1211:state ?state.
                                FILTER (xsd:string(?carf_accredit) = "Y") 
}
}
order by ?state