PREFIX DS1202:<http://data-gov.tw.rpi.edu/vocab/p/1202/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
SELECT distinct ?state (SUM(xsd:integer(?white_inpatients)) as ?Total_white_inpatients) (SUM(xsd:integer(?afr_am_inpatients)) as ?Total_afr_amr_inpatients) (SUM(xsd:integer(?homeless_outpateint)) as ?total_homeless_outpateint) (SUM(xsd:integer(?emergency)) as ?Total_emergency)
WHERE {

GRAPH <http://localhost:3030/myDataset/data/GRAPH_1209> {	
?s DS1202:white_inpatient ?white_inpatients.
?s DS1202:african_american_inpatient ?afr_am_inpatients.
?s DS1202:state ?state .    
}

GRAPH <http://localhost:3030/myDataset/data/GRAPH_1208>  {	
				?s1 DS1202:homeless_outpateint ?homeless_outpateint.
				?s1 DS1202:state ?state .   
}

GRAPH <http://localhost:3030/myDataset/data/GRAPH_1212>  {	
?s2 DS1202:emergency ?emergency.
?s2 DS1202:state ?state.
}}

group by ?state
order by ?state