PREFIX DS1212: <http://logd.tw.rpi.edu/source/data-gov/dataset/1212/vocab/raw/>

SELECT distinct ?state (SUM(xsd:double(?emergency)) as ?total_emergency)
WHERE {  

GRAPH <http://logd.tw.rpi.edu/source/data-gov/dataset/1212/version/1st-anniversary>  {	
				?s1 DS1212:emergency ?emergency.
				?s1 DS1212:state ?state .   
}
}
order by ?state